forum:
    resource: ../src/Forum/Controller
    type: attribute
    prefix: donations/
    name_prefix: donations_

admin:
    resource: ../src/Admin/Controller
    type: attribute
    prefix: admin/donations/
    name_prefix: donations_admin_
